Chatui
kothariji/SyntaxMeets pull request #135
Opened 2021-05-16 15:32 UTC by Lavcodes

2021-05-17 08:05 UTC, kothariji commented
@Lavcodes 

Its not working
![image](https://user-images.githubusercontent.com/60866749/118453255-9dd2d100-b714-11eb-9f84-99d5ade840f8.png)

The user names are not visible
Also that cross icon is colliding with the messages

Make sure you pull the latest code, before creating a pull request

2021-05-18 12:04 UTC, kothariji requested changes
Please make changes as per requested

2021-05-18 13:51 UTC, Lavcodes commented
Made changes. Please review. 
Here's how it would look for two users.
![Screenshot (9)](https://user-images.githubusercontent.com/59924327/118662999-123d6b00-b80e-11eb-9ee9-5d173e326f16.png)
For the "other person"
![Screenshot (10)](https://user-images.githubusercontent.com/59924327/118663129-30a36680-b80e-11eb-88a4-baf18ce1b926.png)

2021-05-21 19:35 UTC, kothariji commented
@Lavcodes, Please check its not working in my end. The close symbol hides, when I scroll down, here is the attached screenshot
![image](https://user-images.githubusercontent.com/60866749/119189502-c0a91080-ba99-11eb-88f1-c3157ea1187e.png)

2022-03-29 04:06 UTC, closed without merging