{{🚀[Feat]: Added Feature to upload files locally}}
kothariji/SyntaxMeets pull request #97
Opened 2021-03-30 12:03 UTC by jainaayush01

Closes Issue: #57

2021-03-31 04:46 UTC, kothariji commented
Hi @jainaayush01, Thank you for the PR.
But actually, we are working on Refactoring and implementing redux. You can see PR #99, so once it is merged, then we will work on this PR for sure.

Please bare with us 🙌 😊

2021-04-05 08:45 UTC, kothariji commented
Hi @jainaayush01, we are done with the refactoring of code, so I would request you to remove the merge conflicts so we can preview the PR, and merge it once done. 🙌

2021-04-05 17:23 UTC, jainaayush01 commented
Done.

2021-04-05 18:00 UTC, kothariji commented
Also, there is a compilation error 
![image](https://user-images.githubusercontent.com/60866749/113607457-d936a600-9666-11eb-9596-0124e3304ebb.png)

Please check once running code in local 🙌

2021-04-05 18:11 UTC, kothariji requested changes
Please do the requested changes

2021-04-05 18:11 UTC, kothariji commented on frontend/syntaxmeets/src/components/SyntaxEditor/SyntaxEditor.js
> +  };
Also please remove that, as we are handling this part in separate component `INPUT`

2021-04-05 18:33 UTC, jainaayush01 commented
> Also, there is a compilation error
> ![image](https://user-images.githubusercontent.com/60866749/113607457-d936a600-9666-11eb-9596-0124e3304ebb.png)
> 
> Please check once running code in local 🙌

my bad i should have checked!! sorry for that

2021-04-07 05:58 UTC, kothariji commented
> I have copied the SyntaxEditor.js file from the main branch here and have added my changes there. Still, I am seeing 2 more file changes. please let me know if some more changes are to be made or should I just make a new PR with an updated codebase.

Preview Link - https://syntaxmeets-6urefc9zf-kothariji.vercel.app/
### Hey @jainaayush01, the PR looks amazing, things are working great 🙌 
⚠️ but there are a few bugs

 - Even if we have explicitly mentionedthat we will accept only  **.c, .cpp, .java, .js, .ts, .clj, .cljs, .cs, .cbl, .cob, .cpy, .erl,**, but then also we are able to upload .jpeg, .exe etc. So can we validate the file extension in handleFileChange function, and if its not valid we can show an alert that, please upload the supported files only.
 
 - Another issue is that currently there are no such restrictions on the size of the file, but if you'll try uploading big files, the socket will be disconnected.  So it can be great if we can restrict the file size for now to max **'10 kb'**.
 
 Please let me know for the same 🙌

2021-04-07 09:26 UTC, jainaayush01 commented
I have fixed the above mentioned bugs if still there's something missing out please let me know.
🙌

2021-04-07 11:24 UTC, kothariji approved these changes
@jainaayush01 tremendous work 🚀 
Thank you for co-operating and doing the suggested changes.  We really appreciate your contribution 🙌 

Keep Contributing 🔥 🙏

2021-04-07 11:27 UTC, merged